// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fileserver/api.proto

package fileserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_fileserver_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_fileserver_api_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type FileStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStream) Reset() {
	*x = FileStream{}
	mi := &file_fileserver_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStream) ProtoMessage() {}

func (x *FileStream) ProtoReflect() protoreflect.Message {
	mi := &file_fileserver_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStream.ProtoReflect.Descriptor instead.
func (*FileStream) Descriptor() ([]byte, []int) {
	return file_fileserver_api_proto_rawDescGZIP(), []int{1}
}

func (x *FileStream) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_fileserver_api_proto protoreflect.FileDescriptor

const file_fileserver_api_proto_rawDesc = "" +
	"\n" +
	"\x14fileserver/api.proto\x12\n" +
	"fileserver\"\x1e\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\"\n" +
	"\n" +
	"FileStream\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk2\x8b\x01\n" +
	"\aService\x12>\n" +
	"\n" +
	"UploadFile\x12\x16.fileserver.FileStream\x1a\x14.fileserver.FileInfo\"\x00(\x01\x12@\n" +
	"\fDownloadFile\x12\x14.fileserver.FileInfo\x1a\x16.fileserver.FileStream\"\x000\x01B\x96\x01\n" +
	"\x0ecom.fileserverB\bApiProtoP\x01Z2github.com/c4t-but-s4d/neo/v2/pkg/proto/fileserver\xa2\x02\x03FXX\xaa\x02\n" +
	"Fileserver\xca\x02\n" +
	"Fileserver\xe2\x02\x16Fileserver\\GPBMetadata\xea\x02\n" +
	"Fileserverb\x06proto3"

var (
	file_fileserver_api_proto_rawDescOnce sync.Once
	file_fileserver_api_proto_rawDescData []byte
)

func file_fileserver_api_proto_rawDescGZIP() []byte {
	file_fileserver_api_proto_rawDescOnce.Do(func() {
		file_fileserver_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fileserver_api_proto_rawDesc), len(file_fileserver_api_proto_rawDesc)))
	})
	return file_fileserver_api_proto_rawDescData
}

var file_fileserver_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fileserver_api_proto_goTypes = []any{
	(*FileInfo)(nil),   // 0: fileserver.FileInfo
	(*FileStream)(nil), // 1: fileserver.FileStream
}
var file_fileserver_api_proto_depIdxs = []int32{
	1, // 0: fileserver.Service.UploadFile:input_type -> fileserver.FileStream
	0, // 1: fileserver.Service.DownloadFile:input_type -> fileserver.FileInfo
	0, // 2: fileserver.Service.UploadFile:output_type -> fileserver.FileInfo
	1, // 3: fileserver.Service.DownloadFile:output_type -> fileserver.FileStream
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fileserver_api_proto_init() }
func file_fileserver_api_proto_init() {
	if File_fileserver_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fileserver_api_proto_rawDesc), len(file_fileserver_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fileserver_api_proto_goTypes,
		DependencyIndexes: file_fileserver_api_proto_depIdxs,
		MessageInfos:      file_fileserver_api_proto_msgTypes,
	}.Build()
	File_fileserver_api_proto = out.File
	file_fileserver_api_proto_goTypes = nil
	file_fileserver_api_proto_depIdxs = nil
}
