run:
  timeout: 5m
  tests: true
  skip-dirs:
    - pkg/apps/.*

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gocritic
    - gofmt
    - goimports
    - gomoddirectives
    - gosimple
    - govet
    - ineffassign
    - importas
    - misspell
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wrapcheck

linters-settings:
  unparam:
    check-exported: false
  unused:
    check-exported: false
  wrapcheck:
    ignoreSigs:
      - (context.Context).Err()
      - fmt.Errorf(
      - errors.New(
      - WrapErrorf

issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude-rules:
    - source: "status\\.Errorf"
      linters:
        - wrapcheck
    - linters:
        - revive
      text: "package-comments:"
    - linters:
        - revive
      text: "exported:"
