run:
  skip-dirs:
    - pkg/apps/.*

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - goimports
    - ifshort
    - misspell
    - noctx
    - prealloc
    - predeclared
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck

linters-settings:
  unparam:
    check-exported: false
  unused:
    check-exported: false

issues:
  exclude-use-default: false
  max-same-issues: 0
