before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: "neo_client"
    main: "./cmd/client"
    binary: "./neo"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

  - id: "dummy"
    main: "./cmd/client"
    binary: "neo"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - "mv neo_client_docker neo_{{ .Version }}"
        - "zip -r neo_{{ .Version }}.zip neo_{{ .Version }}"
        - "rm -rf neo_{{ .Version }}"
        - "mkdir dist/other"
        - "mv neo_{{ .Version }}.zip dist/other/"
        - "ls -lh dist/other/neo_{{ .Version }}.zip"

  - id: "neo_server"
    main: "./cmd/server"
    binary: "./neo_server"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: full_binaries
    format: zip
    builds:
      - "neo_client"
      - "neo_server"
    name_template: "{{ .ProjectName }}_full_{{ .Version }}_{{ .Os }}"
    wrap_in_directory: "{{ .ProjectName }}_full_{{ .Version }}_{{ .Os }}"
    replacements:
      darwin: macOS
      386: i386
      amd64: x64
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - README.md
      - server/config.yml
      - client/config.yml

  - id: server
    format: zip
    builds:
      - "neo_server"
    name_template: "{{ .ProjectName }}_server_{{ .Version }}_{{ .Os }}"
    wrap_in_directory: "{{ .ProjectName }}_server_{{ .Version }}_{{ .Os }}"
    replacements:
      darwin: macOS
      386: i386
      amd64: x64
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - server/*

release:
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"
  extra_files:
    - glob: "./dist/other/*"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
