before:
  hooks:
    - go mod tidy
builds:
  - id: "neo_client"
    main: "./cmd/client"
    binary: "./neo_client/neo"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: "neo_server"
    main: "./cmd/server"
    binary: "./neo_server/neo_server"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - format: zip
    replacements:
      darwin: MacOs
      linux: Linux
      windows: Windows
      386: i386
      amd64: x64
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - README*.md
      - configs/client/config.yml
      - configs/server/config.yml

  - id: client
    format: zip
    builds:
      - "neo_client"
    name_template: "{{ .ProjectName }}_client_{{ .Version }}"
    replacements:
      darwin: MacOs
      linux: Linux
      windows: Windows
      386: i386
      amd64: x64
    files:
      - README.MD
      - neo_client/config.yml
      - neo_client/*
  - id: server
    format: zip
    builds:
      - "neo_server"
    name_template: "{{ .ProjectName }}_server_{{ .Version }}_{{ .Os }}"
    replacements:
      darwin: MacOs
      linux: Linux
      windows: Windows
      386: i386
      amd64: x64
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - README.MD
      - neo_server/config.yml
      - neo_server/data/.keep
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
