before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - &neo-client-build
    id: "neo_client"
    main: "./cmd/client"
    binary: "./neo_client/neo"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

  - <<: *neo-client-build
    id: "neo_client_for_docker"
    goos:
      - linux

  - id: "neo_server"
    main: "./cmd/server"
    binary: "./neo_server/neo_server"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: full_binaries
    format: zip
    builds:
      - "neo_client"
      - "neo_server"
    replacements:
      darwin: macOS
      386: i386
      amd64: x64
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - README.md
      - neo_server/config.yml
      - neo_client/config.yml

  - id: client_for_docker
    format: zip
    builds:
      - "neo_client_for_docker"
    name_template: "{{ .ProjectName }}_client_{{ .Version }}"
    replacements:
      darwin: macOS
      386: i386
      amd64: x64
    files:
      - neo_client/*

  - id: server
    format: zip
    builds:
      - "neo_server"
    name_template: "{{ .ProjectName }}_server_{{ .Version }}_{{ .Os }}"
    replacements:
      darwin: macOS
      386: i386
      amd64: x64
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - neo_server/*

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
