before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: "neo_client"
    main: "./cmd/client"
    binary: "./neo"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: "dummy"
    main: "./cmd/client"
    binary: "neo"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - "mv neo_client_docker neo_{{ .Version }}"
        - "zip -r neo_{{ .Version }}.zip neo_{{ .Version }}"
        - "rm -rf neo_{{ .Version }}"
        - "mkdir dist/other"
        - "mv neo_{{ .Version }}.zip dist/other/"
        - "ls -lh dist/other/neo_{{ .Version }}.zip"
        - "mv neo_server neo_server_{{ .Version }}"
        - "zip -r neo_server_{{ .Version }}.zip neo_server_{{ .Version }}"
        - "rm -rf neo_server_{{ .Version }}"
        - "mv neo_server_{{ .Version }}.zip dist/other/"
        - "ls -lh dist/other/neo_server_{{ .Version }}.zip"

archives:
  - id: "client"
    format: zip
    builds:
      - "neo_client"
    name_template: "{{ .ProjectName }}_client_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "{{ .ProjectName }}_client_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macOS
      amd64: x64
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - README.md
      - client_config.yml
      - exploits/.keep

release:
  prerelease: auto
  name_template: "{{.ProjectName}}-{{.Version}}"
  extra_files:
    - glob: "./dist/other/*"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
