codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "30...60"
  status:
    project:
      default:
        target: 45
    patch: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
