services:
  server:
    build: .
    volumes:
      - "./configs/server/config.yml:/config.yml:ro"
      - "./volumes/data:/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NEO_GRPC_AUTH_KEY: ${GRPC_AUTH_KEY}
      NEO_FARM_PASSWORD: ${FARM_PASSWORD}
      NEO_FARM_URL: ${FARM_URL}
      NEO_DB_PATH: /data/db.db
      NEO_VICTORIALOGS_URL: 'http://victoria-logs:9428'
      NEO_BASE_DIR: '/data/exploits'
    ports:
      - '5005:5005'
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:12.2.0-17142428006-ubuntu
    user: '0'
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./monitoring/cfg/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/cfg/grafana/dashboards:/dashboards
    restart: unless-stopped
    cpus: 2
    mem_limit: 4gb
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-1234}
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_INSTALL_PLUGINS: victoriametrics-logs-datasource
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /dashboards/Home.json
    ports:
      - "3000:3000"

  victoria:
    image: victoriametrics/victoria-metrics:v1.130.0
    user: '0'
    volumes:
      - ./monitoring/cfg/prometheus:/etc/prometheus
      - ./volumes/victoria-metrics:/victoria-metrics-data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "-storageDataPath=/victoria-metrics-data"
      - "-promscrape.config=/etc/prometheus/config.yml"
    restart: unless-stopped
    ports:
      - "8428:8428"

  victoria-logs:
    image: docker.io/victoriametrics/victoria-logs:v1.38.0
    user: '0'
    volumes:
      - ./volumes/victoria-logs:/victoria-logs-data
    command:
      - "-storageDataPath=/victoria-logs-data"
      - "-httpListenAddr=:9428"
    restart: unless-stopped
    ports:
      - "9428:9428"
