[tools]
go = "1.25"
golangci-lint = "2.6.2"

[tasks.go-lint]
description = "Run golangci-lint"
run = "golangci-lint run -v --config .golangci.yml"

[tasks.go-lint-fix]
description = "Run golangci-lint and fix lint issues"
run = "golangci-lint run -v --config .golangci.yml --fix"

[tasks.go-test]
description = "Run go tests"
run = "go test -race -timeout 1m ./..."
