// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: neo.proto

package neo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest_PingType int32

const (
	PingRequest_CONFIG_REQUEST PingRequest_PingType = 0
	PingRequest_HEARTBEAT      PingRequest_PingType = 1
	PingRequest_LEAVE          PingRequest_PingType = 2
)

// Enum value maps for PingRequest_PingType.
var (
	PingRequest_PingType_name = map[int32]string{
		0: "CONFIG_REQUEST",
		1: "HEARTBEAT",
		2: "LEAVE",
	}
	PingRequest_PingType_value = map[string]int32{
		"CONFIG_REQUEST": 0,
		"HEARTBEAT":      1,
		"LEAVE":          2,
	}
)

func (x PingRequest_PingType) Enum() *PingRequest_PingType {
	p := new(PingRequest_PingType)
	*p = x
	return p
}

func (x PingRequest_PingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingRequest_PingType) Descriptor() protoreflect.EnumDescriptor {
	return file_neo_proto_enumTypes[0].Descriptor()
}

func (PingRequest_PingType) Type() protoreflect.EnumType {
	return &file_neo_proto_enumTypes[0]
}

func (x PingRequest_PingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingRequest_PingType.Descriptor instead.
func (PingRequest_PingType) EnumDescriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{7, 0}
}

type TeamBucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teams map[string]string `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TeamBucket) Reset() {
	*x = TeamBucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamBucket) ProtoMessage() {}

func (x *TeamBucket) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamBucket.ProtoReflect.Descriptor instead.
func (*TeamBucket) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{0}
}

func (x *TeamBucket) GetTeams() map[string]string {
	if x != nil {
		return x.Teams
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ExploitConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entrypoint string `protobuf:"bytes,1,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	IsArchive  bool   `protobuf:"varint,2,opt,name=is_archive,json=isArchive,proto3" json:"is_archive,omitempty"`
	RunEvery   string `protobuf:"bytes,3,opt,name=run_every,json=runEvery,proto3" json:"run_every,omitempty"`
	Timeout    string `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *ExploitConfiguration) Reset() {
	*x = ExploitConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExploitConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploitConfiguration) ProtoMessage() {}

func (x *ExploitConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploitConfiguration.ProtoReflect.Descriptor instead.
func (*ExploitConfiguration) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{2}
}

func (x *ExploitConfiguration) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *ExploitConfiguration) GetIsArchive() bool {
	if x != nil {
		return x.IsArchive
	}
	return false
}

func (x *ExploitConfiguration) GetRunEvery() string {
	if x != nil {
		return x.RunEvery
	}
	return ""
}

func (x *ExploitConfiguration) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type ExploitState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExploitId string                `protobuf:"bytes,1,opt,name=exploit_id,json=exploitId,proto3" json:"exploit_id,omitempty"`
	Version   int64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	File      *FileInfo             `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Disabled  bool                  `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Endless   bool                  `protobuf:"varint,5,opt,name=endless,proto3" json:"endless,omitempty"`
	Config    *ExploitConfiguration `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ExploitState) Reset() {
	*x = ExploitState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExploitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploitState) ProtoMessage() {}

func (x *ExploitState) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploitState.ProtoReflect.Descriptor instead.
func (*ExploitState) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{3}
}

func (x *ExploitState) GetExploitId() string {
	if x != nil {
		return x.ExploitId
	}
	return ""
}

func (x *ExploitState) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ExploitState) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ExploitState) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *ExploitState) GetEndless() bool {
	if x != nil {
		return x.Endless
	}
	return false
}

func (x *ExploitState) GetConfig() *ExploitConfiguration {
	if x != nil {
		return x.Config
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FarmUrl      string   `protobuf:"bytes,1,opt,name=farm_url,json=farmUrl,proto3" json:"farm_url,omitempty"`
	FarmPassword string   `protobuf:"bytes,2,opt,name=farm_password,json=farmPassword,proto3" json:"farm_password,omitempty"`
	FlagRegexp   string   `protobuf:"bytes,3,opt,name=flag_regexp,json=flagRegexp,proto3" json:"flag_regexp,omitempty"`
	PingEvery    string   `protobuf:"bytes,4,opt,name=ping_every,json=pingEvery,proto3" json:"ping_every,omitempty"`
	SubmitEvery  string   `protobuf:"bytes,5,opt,name=submit_every,json=submitEvery,proto3" json:"submit_every,omitempty"`
	Environ      []string `protobuf:"bytes,6,rep,name=environ,proto3" json:"environ,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{4}
}

func (x *Config) GetFarmUrl() string {
	if x != nil {
		return x.FarmUrl
	}
	return ""
}

func (x *Config) GetFarmPassword() string {
	if x != nil {
		return x.FarmPassword
	}
	return ""
}

func (x *Config) GetFlagRegexp() string {
	if x != nil {
		return x.FlagRegexp
	}
	return ""
}

func (x *Config) GetPingEvery() string {
	if x != nil {
		return x.PingEvery
	}
	return ""
}

func (x *Config) GetSubmitEvery() string {
	if x != nil {
		return x.SubmitEvery
	}
	return ""
}

func (x *Config) GetEnviron() []string {
	if x != nil {
		return x.Environ
	}
	return nil
}

type ServerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Ping distribution by client
	ClientTeamMap map[string]*TeamBucket `protobuf:"bytes,1,rep,name=client_team_map,json=clientTeamMap,proto3" json:"client_team_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Exploits      []*ExploitState        `protobuf:"bytes,2,rep,name=exploits,proto3" json:"exploits,omitempty"`
	Config        *Config                `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{5}
}

func (x *ServerState) GetClientTeamMap() map[string]*TeamBucket {
	if x != nil {
		return x.ClientTeamMap
	}
	return nil
}

func (x *ServerState) GetExploits() []*ExploitState {
	if x != nil {
		return x.Exploits
	}
	return nil
}

func (x *ServerState) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type FileStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (x *FileStream) Reset() {
	*x = FileStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStream) ProtoMessage() {}

func (x *FileStream) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStream.ProtoReflect.Descriptor instead.
func (*FileStream) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{6}
}

func (x *FileStream) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     PingRequest_PingType `protobuf:"varint,1,opt,name=type,proto3,enum=neo.PingRequest_PingType" json:"type,omitempty"`
	ClientId string               `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Weight   int32                `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{7}
}

func (x *PingRequest) GetType() PingRequest_PingType {
	if x != nil {
		return x.Type
	}
	return PingRequest_CONFIG_REQUEST
}

func (x *PingRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PingRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *ServerState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetState() *ServerState {
	if x != nil {
		return x.State
	}
	return nil
}

type ExploitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExploitId string `protobuf:"bytes,1,opt,name=exploit_id,json=exploitId,proto3" json:"exploit_id,omitempty"`
}

func (x *ExploitRequest) Reset() {
	*x = ExploitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExploitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploitRequest) ProtoMessage() {}

func (x *ExploitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploitRequest.ProtoReflect.Descriptor instead.
func (*ExploitRequest) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{9}
}

func (x *ExploitRequest) GetExploitId() string {
	if x != nil {
		return x.ExploitId
	}
	return ""
}

type ExploitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *ExploitState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ExploitResponse) Reset() {
	*x = ExploitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExploitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExploitResponse) ProtoMessage() {}

func (x *ExploitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExploitResponse.ProtoReflect.Descriptor instead.
func (*ExploitResponse) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{10}
}

func (x *ExploitResponse) GetState() *ExploitState {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateExploitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *ExploitState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *UpdateExploitRequest) Reset() {
	*x = UpdateExploitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExploitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExploitRequest) ProtoMessage() {}

func (x *UpdateExploitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExploitRequest.ProtoReflect.Descriptor instead.
func (*UpdateExploitRequest) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateExploitRequest) GetState() *ExploitState {
	if x != nil {
		return x.State
	}
	return nil
}

type UpdateExploitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *ExploitState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *UpdateExploitResponse) Reset() {
	*x = UpdateExploitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExploitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExploitResponse) ProtoMessage() {}

func (x *UpdateExploitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExploitResponse.ProtoReflect.Descriptor instead.
func (*UpdateExploitResponse) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateExploitResponse) GetState() *ExploitState {
	if x != nil {
		return x.State
	}
	return nil
}

type SingleRunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExploitId string `protobuf:"bytes,1,opt,name=exploit_id,json=exploitId,proto3" json:"exploit_id,omitempty"`
}

func (x *SingleRunRequest) Reset() {
	*x = SingleRunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRunRequest) ProtoMessage() {}

func (x *SingleRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRunRequest.ProtoReflect.Descriptor instead.
func (*SingleRunRequest) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{13}
}

func (x *SingleRunRequest) GetExploitId() string {
	if x != nil {
		return x.ExploitId
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{14}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neo_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_neo_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_neo_proto_rawDescGZIP(), []int{15}
}

var File_neo_proto protoreflect.FileDescriptor

var file_neo_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6e, 0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6e, 0x65, 0x6f,
	0x22, 0x78, 0x0a, 0x0a, 0x54, 0x65, 0x61, 0x6d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x30,
	0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6e, 0x65, 0x6f, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x54,
	0x65, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73,
	0x1a, 0x38, 0x0a, 0x0a, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1e, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x14, 0x45,
	0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x75, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x75, 0x6e, 0x45, 0x76, 0x65, 0x72, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0xd3, 0x01, 0x0a, 0x0c, 0x45, 0x78,
	0x70, 0x6c, 0x6f, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x6c, 0x6f, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x73, 0x12, 0x31, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6e,
	0x65, 0x6f, 0x2e, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22,
	0xc5, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x61,
	0x72, 0x6d, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61,
	0x72, 0x6d, 0x55, 0x72, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x61, 0x72, 0x6d, 0x5f, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x61,
	0x72, 0x6d, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6c,
	0x61, 0x67, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x66, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x67, 0x65, 0x78, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x69, 0x6e, 0x67, 0x5f, 0x65, 0x76, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x45, 0x76, 0x65, 0x72, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x22, 0x81, 0x02, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x65, 0x61,
	0x6d, 0x4d, 0x61, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x45, 0x78, 0x70,
	0x6c, 0x6f, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6c, 0x6f,
	0x69, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x51, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x22, 0x0a, 0x0a, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x22,
	0xab, 0x01, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e,
	0x6e, 0x65, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x22, 0x38, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x0e, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x02, 0x22, 0x36, 0x0a,
	0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e,
	0x65, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2f, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x6c, 0x6f,
	0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x70,
	0x6c, 0x6f, 0x69, 0x74, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x0f, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x45,
	0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x22, 0x3f, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x6c,
	0x6f, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65, 0x6f, 0x2e,
	0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x40, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70,
	0x6c, 0x6f, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x65,
	0x6f, 0x2e, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x31, 0x0a, 0x10, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70,
	0x6c, 0x6f, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x07, 0x0a,
	0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xf8, 0x03, 0x0a, 0x0e, 0x45, 0x78, 0x70, 0x6c, 0x6f,
	0x69, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x10, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0f, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x0d, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x28, 0x01, 0x12, 0x32, 0x0a, 0x0c, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x0d, 0x2e, 0x6e, 0x65, 0x6f,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x6e, 0x65, 0x6f, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x00, 0x30, 0x01, 0x12, 0x36,
	0x0a, 0x07, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x6e, 0x65, 0x6f, 0x2e,
	0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x12, 0x19, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x70, 0x6c, 0x6f, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x2e, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0c, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x1a, 0x0a, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x31, 0x0a, 0x11, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x0a, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0c, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x30, 0x0a, 0x09, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x75, 0x6e,
	0x12, 0x15, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x75, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x11, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x0a, 0x2e, 0x6e, 0x65, 0x6f,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x6e, 0x65, 0x6f, 0x2e, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x6f, 0x6d, 0x6f, 0x2d, 0x6d, 0x6f, 0x6e, 0x64, 0x72, 0x65, 0x67, 0x61, 0x6e, 0x74, 0x6f,
	0x2f, 0x6e, 0x65, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_neo_proto_rawDescOnce sync.Once
	file_neo_proto_rawDescData = file_neo_proto_rawDesc
)

func file_neo_proto_rawDescGZIP() []byte {
	file_neo_proto_rawDescOnce.Do(func() {
		file_neo_proto_rawDescData = protoimpl.X.CompressGZIP(file_neo_proto_rawDescData)
	})
	return file_neo_proto_rawDescData
}

var file_neo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neo_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_neo_proto_goTypes = []interface{}{
	(PingRequest_PingType)(0),     // 0: neo.PingRequest.PingType
	(*TeamBucket)(nil),            // 1: neo.TeamBucket
	(*FileInfo)(nil),              // 2: neo.FileInfo
	(*ExploitConfiguration)(nil),  // 3: neo.ExploitConfiguration
	(*ExploitState)(nil),          // 4: neo.ExploitState
	(*Config)(nil),                // 5: neo.Config
	(*ServerState)(nil),           // 6: neo.ServerState
	(*FileStream)(nil),            // 7: neo.FileStream
	(*PingRequest)(nil),           // 8: neo.PingRequest
	(*PingResponse)(nil),          // 9: neo.PingResponse
	(*ExploitRequest)(nil),        // 10: neo.ExploitRequest
	(*ExploitResponse)(nil),       // 11: neo.ExploitResponse
	(*UpdateExploitRequest)(nil),  // 12: neo.UpdateExploitRequest
	(*UpdateExploitResponse)(nil), // 13: neo.UpdateExploitResponse
	(*SingleRunRequest)(nil),      // 14: neo.SingleRunRequest
	(*Command)(nil),               // 15: neo.Command
	(*Empty)(nil),                 // 16: neo.Empty
	nil,                           // 17: neo.TeamBucket.TeamsEntry
	nil,                           // 18: neo.ServerState.ClientTeamMapEntry
}
var file_neo_proto_depIdxs = []int32{
	17, // 0: neo.TeamBucket.teams:type_name -> neo.TeamBucket.TeamsEntry
	2,  // 1: neo.ExploitState.file:type_name -> neo.FileInfo
	3,  // 2: neo.ExploitState.config:type_name -> neo.ExploitConfiguration
	18, // 3: neo.ServerState.client_team_map:type_name -> neo.ServerState.ClientTeamMapEntry
	4,  // 4: neo.ServerState.exploits:type_name -> neo.ExploitState
	5,  // 5: neo.ServerState.config:type_name -> neo.Config
	0,  // 6: neo.PingRequest.type:type_name -> neo.PingRequest.PingType
	6,  // 7: neo.PingResponse.state:type_name -> neo.ServerState
	4,  // 8: neo.ExploitResponse.state:type_name -> neo.ExploitState
	4,  // 9: neo.UpdateExploitRequest.state:type_name -> neo.ExploitState
	4,  // 10: neo.UpdateExploitResponse.state:type_name -> neo.ExploitState
	1,  // 11: neo.ServerState.ClientTeamMapEntry.value:type_name -> neo.TeamBucket
	8,  // 12: neo.ExploitManager.Ping:input_type -> neo.PingRequest
	7,  // 13: neo.ExploitManager.UploadFile:input_type -> neo.FileStream
	2,  // 14: neo.ExploitManager.DownloadFile:input_type -> neo.FileInfo
	10, // 15: neo.ExploitManager.Exploit:input_type -> neo.ExploitRequest
	12, // 16: neo.ExploitManager.UpdateExploit:input_type -> neo.UpdateExploitRequest
	15, // 17: neo.ExploitManager.BroadcastCommand:input_type -> neo.Command
	16, // 18: neo.ExploitManager.BroadcastRequests:input_type -> neo.Empty
	14, // 19: neo.ExploitManager.SingleRun:input_type -> neo.SingleRunRequest
	16, // 20: neo.ExploitManager.SingleRunRequests:input_type -> neo.Empty
	9,  // 21: neo.ExploitManager.Ping:output_type -> neo.PingResponse
	2,  // 22: neo.ExploitManager.UploadFile:output_type -> neo.FileInfo
	7,  // 23: neo.ExploitManager.DownloadFile:output_type -> neo.FileStream
	11, // 24: neo.ExploitManager.Exploit:output_type -> neo.ExploitResponse
	13, // 25: neo.ExploitManager.UpdateExploit:output_type -> neo.UpdateExploitResponse
	16, // 26: neo.ExploitManager.BroadcastCommand:output_type -> neo.Empty
	15, // 27: neo.ExploitManager.BroadcastRequests:output_type -> neo.Command
	16, // 28: neo.ExploitManager.SingleRun:output_type -> neo.Empty
	14, // 29: neo.ExploitManager.SingleRunRequests:output_type -> neo.SingleRunRequest
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_neo_proto_init() }
func file_neo_proto_init() {
	if File_neo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_neo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamBucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExploitConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExploitState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExploitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExploitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExploitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExploitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleRunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neo_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_neo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neo_proto_goTypes,
		DependencyIndexes: file_neo_proto_depIdxs,
		EnumInfos:         file_neo_proto_enumTypes,
		MessageInfos:      file_neo_proto_msgTypes,
	}.Build()
	File_neo_proto = out.File
	file_neo_proto_rawDesc = nil
	file_neo_proto_goTypes = nil
	file_neo_proto_depIdxs = nil
}
