// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package neo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ExploitManagerClient is the client API for ExploitManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExploitManagerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (ExploitManager_UploadFileClient, error)
	DownloadFile(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (ExploitManager_DownloadFileClient, error)
	Exploit(ctx context.Context, in *ExploitRequest, opts ...grpc.CallOption) (*ExploitResponse, error)
	UpdateExploit(ctx context.Context, in *UpdateExploitRequest, opts ...grpc.CallOption) (*UpdateExploitResponse, error)
	BroadcastCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Empty, error)
	BroadcastRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ExploitManager_BroadcastRequestsClient, error)
	SingleRun(ctx context.Context, in *ExploitRequest, opts ...grpc.CallOption) (*Empty, error)
	SingleRunRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ExploitManager_SingleRunRequestsClient, error)
}

type exploitManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewExploitManagerClient(cc grpc.ClientConnInterface) ExploitManagerClient {
	return &exploitManagerClient{cc}
}

func (c *exploitManagerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/ExploitManager/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploitManagerClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (ExploitManager_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ExploitManager_serviceDesc.Streams[0], "/ExploitManager/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &exploitManagerUploadFileClient{stream}
	return x, nil
}

type ExploitManager_UploadFileClient interface {
	Send(*FileStream) error
	CloseAndRecv() (*FileInfo, error)
	grpc.ClientStream
}

type exploitManagerUploadFileClient struct {
	grpc.ClientStream
}

func (x *exploitManagerUploadFileClient) Send(m *FileStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *exploitManagerUploadFileClient) CloseAndRecv() (*FileInfo, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exploitManagerClient) DownloadFile(ctx context.Context, in *FileInfo, opts ...grpc.CallOption) (ExploitManager_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ExploitManager_serviceDesc.Streams[1], "/ExploitManager/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &exploitManagerDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ExploitManager_DownloadFileClient interface {
	Recv() (*FileStream, error)
	grpc.ClientStream
}

type exploitManagerDownloadFileClient struct {
	grpc.ClientStream
}

func (x *exploitManagerDownloadFileClient) Recv() (*FileStream, error) {
	m := new(FileStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exploitManagerClient) Exploit(ctx context.Context, in *ExploitRequest, opts ...grpc.CallOption) (*ExploitResponse, error) {
	out := new(ExploitResponse)
	err := c.cc.Invoke(ctx, "/ExploitManager/Exploit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploitManagerClient) UpdateExploit(ctx context.Context, in *UpdateExploitRequest, opts ...grpc.CallOption) (*UpdateExploitResponse, error) {
	out := new(UpdateExploitResponse)
	err := c.cc.Invoke(ctx, "/ExploitManager/UpdateExploit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploitManagerClient) BroadcastCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ExploitManager/BroadcastCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploitManagerClient) BroadcastRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ExploitManager_BroadcastRequestsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ExploitManager_serviceDesc.Streams[2], "/ExploitManager/BroadcastRequests", opts...)
	if err != nil {
		return nil, err
	}
	x := &exploitManagerBroadcastRequestsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ExploitManager_BroadcastRequestsClient interface {
	Recv() (*Command, error)
	grpc.ClientStream
}

type exploitManagerBroadcastRequestsClient struct {
	grpc.ClientStream
}

func (x *exploitManagerBroadcastRequestsClient) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exploitManagerClient) SingleRun(ctx context.Context, in *ExploitRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ExploitManager/SingleRun", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exploitManagerClient) SingleRunRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ExploitManager_SingleRunRequestsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ExploitManager_serviceDesc.Streams[3], "/ExploitManager/SingleRunRequests", opts...)
	if err != nil {
		return nil, err
	}
	x := &exploitManagerSingleRunRequestsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ExploitManager_SingleRunRequestsClient interface {
	Recv() (*ExploitRequest, error)
	grpc.ClientStream
}

type exploitManagerSingleRunRequestsClient struct {
	grpc.ClientStream
}

func (x *exploitManagerSingleRunRequestsClient) Recv() (*ExploitRequest, error) {
	m := new(ExploitRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ExploitManagerServer is the server API for ExploitManager service.
// All implementations must embed UnimplementedExploitManagerServer
// for forward compatibility
type ExploitManagerServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	UploadFile(ExploitManager_UploadFileServer) error
	DownloadFile(*FileInfo, ExploitManager_DownloadFileServer) error
	Exploit(context.Context, *ExploitRequest) (*ExploitResponse, error)
	UpdateExploit(context.Context, *UpdateExploitRequest) (*UpdateExploitResponse, error)
	BroadcastCommand(context.Context, *Command) (*Empty, error)
	BroadcastRequests(*Empty, ExploitManager_BroadcastRequestsServer) error
	SingleRun(context.Context, *ExploitRequest) (*Empty, error)
	SingleRunRequests(*Empty, ExploitManager_SingleRunRequestsServer) error
	mustEmbedUnimplementedExploitManagerServer()
}

// UnimplementedExploitManagerServer must be embedded to have forward compatible implementations.
type UnimplementedExploitManagerServer struct {
}

func (UnimplementedExploitManagerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedExploitManagerServer) UploadFile(ExploitManager_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedExploitManagerServer) DownloadFile(*FileInfo, ExploitManager_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedExploitManagerServer) Exploit(context.Context, *ExploitRequest) (*ExploitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exploit not implemented")
}
func (UnimplementedExploitManagerServer) UpdateExploit(context.Context, *UpdateExploitRequest) (*UpdateExploitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExploit not implemented")
}
func (UnimplementedExploitManagerServer) BroadcastCommand(context.Context, *Command) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastCommand not implemented")
}
func (UnimplementedExploitManagerServer) BroadcastRequests(*Empty, ExploitManager_BroadcastRequestsServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadcastRequests not implemented")
}
func (UnimplementedExploitManagerServer) SingleRun(context.Context, *ExploitRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleRun not implemented")
}
func (UnimplementedExploitManagerServer) SingleRunRequests(*Empty, ExploitManager_SingleRunRequestsServer) error {
	return status.Errorf(codes.Unimplemented, "method SingleRunRequests not implemented")
}
func (UnimplementedExploitManagerServer) mustEmbedUnimplementedExploitManagerServer() {}

// UnsafeExploitManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExploitManagerServer will
// result in compilation errors.
type UnsafeExploitManagerServer interface {
	mustEmbedUnimplementedExploitManagerServer()
}

func RegisterExploitManagerServer(s grpc.ServiceRegistrar, srv ExploitManagerServer) {
	s.RegisterService(&_ExploitManager_serviceDesc, srv)
}

func _ExploitManager_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploitManagerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExploitManager/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploitManagerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploitManager_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExploitManagerServer).UploadFile(&exploitManagerUploadFileServer{stream})
}

type ExploitManager_UploadFileServer interface {
	SendAndClose(*FileInfo) error
	Recv() (*FileStream, error)
	grpc.ServerStream
}

type exploitManagerUploadFileServer struct {
	grpc.ServerStream
}

func (x *exploitManagerUploadFileServer) SendAndClose(m *FileInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *exploitManagerUploadFileServer) Recv() (*FileStream, error) {
	m := new(FileStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ExploitManager_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExploitManagerServer).DownloadFile(m, &exploitManagerDownloadFileServer{stream})
}

type ExploitManager_DownloadFileServer interface {
	Send(*FileStream) error
	grpc.ServerStream
}

type exploitManagerDownloadFileServer struct {
	grpc.ServerStream
}

func (x *exploitManagerDownloadFileServer) Send(m *FileStream) error {
	return x.ServerStream.SendMsg(m)
}

func _ExploitManager_Exploit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExploitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploitManagerServer).Exploit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExploitManager/Exploit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploitManagerServer).Exploit(ctx, req.(*ExploitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploitManager_UpdateExploit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExploitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploitManagerServer).UpdateExploit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExploitManager/UpdateExploit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploitManagerServer).UpdateExploit(ctx, req.(*UpdateExploitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploitManager_BroadcastCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploitManagerServer).BroadcastCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExploitManager/BroadcastCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploitManagerServer).BroadcastCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploitManager_BroadcastRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExploitManagerServer).BroadcastRequests(m, &exploitManagerBroadcastRequestsServer{stream})
}

type ExploitManager_BroadcastRequestsServer interface {
	Send(*Command) error
	grpc.ServerStream
}

type exploitManagerBroadcastRequestsServer struct {
	grpc.ServerStream
}

func (x *exploitManagerBroadcastRequestsServer) Send(m *Command) error {
	return x.ServerStream.SendMsg(m)
}

func _ExploitManager_SingleRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExploitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExploitManagerServer).SingleRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExploitManager/SingleRun",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExploitManagerServer).SingleRun(ctx, req.(*ExploitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExploitManager_SingleRunRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExploitManagerServer).SingleRunRequests(m, &exploitManagerSingleRunRequestsServer{stream})
}

type ExploitManager_SingleRunRequestsServer interface {
	Send(*ExploitRequest) error
	grpc.ServerStream
}

type exploitManagerSingleRunRequestsServer struct {
	grpc.ServerStream
}

func (x *exploitManagerSingleRunRequestsServer) Send(m *ExploitRequest) error {
	return x.ServerStream.SendMsg(m)
}

var _ExploitManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExploitManager",
	HandlerType: (*ExploitManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ExploitManager_Ping_Handler,
		},
		{
			MethodName: "Exploit",
			Handler:    _ExploitManager_Exploit_Handler,
		},
		{
			MethodName: "UpdateExploit",
			Handler:    _ExploitManager_UpdateExploit_Handler,
		},
		{
			MethodName: "BroadcastCommand",
			Handler:    _ExploitManager_BroadcastCommand_Handler,
		},
		{
			MethodName: "SingleRun",
			Handler:    _ExploitManager_SingleRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _ExploitManager_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _ExploitManager_DownloadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BroadcastRequests",
			Handler:       _ExploitManager_BroadcastRequests_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SingleRunRequests",
			Handler:       _ExploitManager_SingleRunRequests_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "neo.proto",
}
