{
 "title": "Neo dash",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "client", "label": "Client ID", "query": { "query": "label_values(client_id)" } },
   { "name": "target", "label": "Target team name", "query": { "query": "label_values(target_id)" } },
   { "name": "exploit", "label": "Exploit name", "query": { "query": "label_values(exploit_id)" } },
   { "name": "farm_sploit", "label": "Farm Exploit", "query": { "query": "label_values(sploit)" } },
   {
    "name": "farm_status",
    "label": "Farm Flag status",
    "query": {
     "query": "label_values(flags_submitted_total,status)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Neo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total teams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_teams{job=\"s4d_farm_celery\"}",
     "legendFormat": "API"
    }
   ]
  },
  {
   "title": "Jobs per runner",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (client_id, queue_type) (neo_exploit_queue_max_jobs)",
     "legendFormat": "{{queue_type}}@{{client_id}}"
    }
   ]
  },
  {
   "title": "Teams per runner",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (client_id) (neo_exploit_runner_teams)",
     "legendFormat": "{{ client_id }}"
    }
   ]
  },
  {
   "title": "Runners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_info{job=\"neo_runner\"})",
     "legendFormat": "Runners"
    }
   ]
  },
  {
   "title": "Flags by exploit and team",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (target_id, exploit_id) (rate(neo_exploit_runner_flags_submitted_total{client_id=~\"$client\", exploit_id=~\"$exploit\", target_id=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{exploit_id}}/{{target_id}}"
    }
   ]
  },
  {
   "title": "Exploit statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (exploit_id, exploit_version) (rate(neo_exploit_queue_exploits_failed_total{client_id=~\"$client\", exploit_id=~\"$exploit\"}[$__rate_interval]))",
     "legendFormat": "failed {{exploit_id}}_{{exploit_version}}"
    },
    {
     "expr": "sum by (exploit_id, exploit_version) (rate(neo_exploit_queue_exploits_finished_total{client_id=~\"$client\", exploit_id=~\"$exploit\"}[$__rate_interval]))",
     "legendFormat": "finished {{exploit_id}}_{{exploit_version}}"
    }
   ]
  },
  {
   "title": "Active exploits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (exploit_id, exploit_version) (neo_exploit_queue_exploit_instances_running{client_id=~\"$client\", exploit_id=~\"$exploit\"})",
     "legendFormat": "{{exploit_id}}_{{exploit_version}}"
    }
   ]
  },
  {
   "title": "Flags by exploit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (exploit_id) (rate(neo_exploit_runner_flags_submitted_total{client_id=~\"$client\", exploit_id=~\"$exploit\", target_id=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{exploit_id}}"
    }
   ]
  },
  {
   "title": "Flags by exploit per version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (exploit_id, exploit_version) (rate(neo_exploit_runner_flags_submitted_total{client_id=~\"$client\", exploit_id=~\"$exploit\", target_id=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{exploit_id}}_{{exploit_version}}"
    }
   ]
  },
  {
   "title": "Flags by team",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (target_id) (rate(neo_exploit_runner_flags_submitted_total{client_id=~\"$client\", exploit_id=~\"$exploit\", target_id=~\"$target\"}[$__rate_interval]))",
     "legendFormat": "{{target_id}}"
    }
   ]
  },
  {
   "title": "Attacks",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by (status, sploit, team) (delta(flags_submitted_total{status=~\"$farm_status\", sploit=~\"$farm_sploit\", team=~\"$target\"}[1m]))",
     "legendFormat": "{{sploit}}/{{team}} - {{status}}"
    }
   ]
  },
  { "title": "Farm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Flags queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (sploit, team) (flags_queued{sploit=~\"$farm_sploit\", team=~\"$target\"})",
     "legendFormat": "{{ sploit }} / {{ team }}"
    }
   ]
  },
  {
   "title": "Flags submitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (sploit, team, status) (rate(flags_submitted_total{sploit=~\"$farm_sploit\", team=~\"$target\", status=~\"$farm_status\"}[$__rate_interval]))",
     "legendFormat": "{{ sploit }} / {{ team }} - {{ status }}"
    }
   ]
  }
 ]
}