// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: logs/api.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exploit       string                 `protobuf:"bytes,1,opt,name=exploit,proto3" json:"exploit,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Team          string                 `protobuf:"bytes,5,opt,name=team,proto3" json:"team,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_logs_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_logs_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_logs_api_proto_rawDescGZIP(), []int{0}
}

func (x *LogLine) GetExploit() string {
	if x != nil {
		return x.Exploit
	}
	return ""
}

func (x *LogLine) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *LogLine) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type AddLogLinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*LogLine             `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLogLinesRequest) Reset() {
	*x = AddLogLinesRequest{}
	mi := &file_logs_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLogLinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLogLinesRequest) ProtoMessage() {}

func (x *AddLogLinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLogLinesRequest.ProtoReflect.Descriptor instead.
func (*AddLogLinesRequest) Descriptor() ([]byte, []int) {
	return file_logs_api_proto_rawDescGZIP(), []int{1}
}

func (x *AddLogLinesRequest) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type SearchLogLinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exploit       string                 `protobuf:"bytes,1,opt,name=exploit,proto3" json:"exploit,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	LastToken     string                 `protobuf:"bytes,4,opt,name=last_token,json=lastToken,proto3" json:"last_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogLinesRequest) Reset() {
	*x = SearchLogLinesRequest{}
	mi := &file_logs_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogLinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogLinesRequest) ProtoMessage() {}

func (x *SearchLogLinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logs_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogLinesRequest.ProtoReflect.Descriptor instead.
func (*SearchLogLinesRequest) Descriptor() ([]byte, []int) {
	return file_logs_api_proto_rawDescGZIP(), []int{2}
}

func (x *SearchLogLinesRequest) GetExploit() string {
	if x != nil {
		return x.Exploit
	}
	return ""
}

func (x *SearchLogLinesRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SearchLogLinesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchLogLinesRequest) GetLastToken() string {
	if x != nil {
		return x.LastToken
	}
	return ""
}

type SearchLogLinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*LogLine             `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	LastToken     string                 `protobuf:"bytes,2,opt,name=last_token,json=lastToken,proto3" json:"last_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogLinesResponse) Reset() {
	*x = SearchLogLinesResponse{}
	mi := &file_logs_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogLinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogLinesResponse) ProtoMessage() {}

func (x *SearchLogLinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logs_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogLinesResponse.ProtoReflect.Descriptor instead.
func (*SearchLogLinesResponse) Descriptor() ([]byte, []int) {
	return file_logs_api_proto_rawDescGZIP(), []int{3}
}

func (x *SearchLogLinesResponse) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *SearchLogLinesResponse) GetLastToken() string {
	if x != nil {
		return x.LastToken
	}
	return ""
}

var File_logs_api_proto protoreflect.FileDescriptor

const file_logs_api_proto_rawDesc = "" +
	"\n" +
	"\x0elogs/api.proto\x12\x04logs\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\aLogLine\x12\x18\n" +
	"\aexploit\x18\x01 \x01(\tR\aexploit\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x12\n" +
	"\x04team\x18\x05 \x01(\tR\x04team\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"9\n" +
	"\x12AddLogLinesRequest\x12#\n" +
	"\x05lines\x18\x01 \x03(\v2\r.logs.LogLineR\x05lines\"\x80\x01\n" +
	"\x15SearchLogLinesRequest\x12\x18\n" +
	"\aexploit\x18\x01 \x01(\tR\aexploit\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1d\n" +
	"\n" +
	"last_token\x18\x04 \x01(\tR\tlastToken\"\\\n" +
	"\x16SearchLogLinesResponse\x12#\n" +
	"\x05lines\x18\x01 \x03(\v2\r.logs.LogLineR\x05lines\x12\x1d\n" +
	"\n" +
	"last_token\x18\x02 \x01(\tR\tlastToken2\x9d\x01\n" +
	"\aService\x12A\n" +
	"\vAddLogLines\x12\x18.logs.AddLogLinesRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x0eSearchLogLines\x12\x1b.logs.SearchLogLinesRequest\x1a\x1c.logs.SearchLogLinesResponse\"\x000\x01Br\n" +
	"\bcom.logsB\bApiProtoP\x01Z,github.com/c4t-but-s4d/neo/v2/pkg/proto/logs\xa2\x02\x03LXX\xaa\x02\x04Logs\xca\x02\x04Logs\xe2\x02\x10Logs\\GPBMetadata\xea\x02\x04Logsb\x06proto3"

var (
	file_logs_api_proto_rawDescOnce sync.Once
	file_logs_api_proto_rawDescData []byte
)

func file_logs_api_proto_rawDescGZIP() []byte {
	file_logs_api_proto_rawDescOnce.Do(func() {
		file_logs_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logs_api_proto_rawDesc), len(file_logs_api_proto_rawDesc)))
	})
	return file_logs_api_proto_rawDescData
}

var file_logs_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_logs_api_proto_goTypes = []any{
	(*LogLine)(nil),                // 0: logs.LogLine
	(*AddLogLinesRequest)(nil),     // 1: logs.AddLogLinesRequest
	(*SearchLogLinesRequest)(nil),  // 2: logs.SearchLogLinesRequest
	(*SearchLogLinesResponse)(nil), // 3: logs.SearchLogLinesResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_logs_api_proto_depIdxs = []int32{
	4, // 0: logs.LogLine.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: logs.AddLogLinesRequest.lines:type_name -> logs.LogLine
	0, // 2: logs.SearchLogLinesResponse.lines:type_name -> logs.LogLine
	1, // 3: logs.Service.AddLogLines:input_type -> logs.AddLogLinesRequest
	2, // 4: logs.Service.SearchLogLines:input_type -> logs.SearchLogLinesRequest
	5, // 5: logs.Service.AddLogLines:output_type -> google.protobuf.Empty
	3, // 6: logs.Service.SearchLogLines:output_type -> logs.SearchLogLinesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_logs_api_proto_init() }
func file_logs_api_proto_init() {
	if File_logs_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logs_api_proto_rawDesc), len(file_logs_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logs_api_proto_goTypes,
		DependencyIndexes: file_logs_api_proto_depIdxs,
		MessageInfos:      file_logs_api_proto_msgTypes,
	}.Build()
	File_logs_api_proto = out.File
	file_logs_api_proto_goTypes = nil
	file_logs_api_proto_depIdxs = nil
}
